version: '3.8'

services:
  pocket-poktroll-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5173:5173
    networks:
      - default
  pocket-poktroll-explorer-backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    ports:
      - 3005:3005
    networks:
      - default
